# -*- coding: utf-8 -*-
"""Document loading.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B_SntCDM28K0bMFJwladCBKjd0ayFZy3

# Document loading
"""

"""
Document Loader Module
Handles PDF and DOCX file loading and text extraction

Uses PyMuPDF (fitz) for PDF extraction
"""
import os
from typing import List, Dict
import fitz  # PyMuPDF
from docx import Document

class DocumentLoader:
    """Load and extract text from PDF and DOCX files"""

    def __init__(self):
        self.supported_formats = ['.pdf', '.docx']

    def load_pdf(self, file_path: str) -> str:
        """Load PDF using PyMuPDF (fast and efficient)"""
        try:
            doc = fitz.open(file_path)
            text = ""
            for page in doc:
                text += page.get_text()
            doc.close()
            return text
        except Exception as e:
            raise Exception(f"Error loading PDF: {str(e)}")

    def load_docx(self, file_path: str) -> str:
        """Load DOCX file"""
        try:
            doc = Document(file_path)
            text = ""
            for paragraph in doc.paragraphs:
                text += paragraph.text + "\n"
            return text
        except Exception as e:
            raise Exception(f"Error loading DOCX: {str(e)}")

    def load_document(self, file_path: str) -> Dict:
        """
        Main method to load any supported document

        Args:
            file_path: Path to the document

        Returns:
            Dictionary with text content and metadata
        """
        if not os.path.exists(file_path):
            raise FileNotFoundError(f"File not found: {file_path}")

        file_ext = os.path.splitext(file_path)[1].lower()

        if file_ext not in self.supported_formats:
            raise ValueError(f"Unsupported file format: {file_ext}")

        # Extract text based on file type
        if file_ext == '.pdf':
            text = self.load_pdf(file_path)
        elif file_ext == '.docx':
            text = self.load_docx(file_path)

        # Prepare metadata
        metadata = {
            'source': os.path.basename(file_path),
            'file_path': file_path,
            'file_type': file_ext,
            'length': len(text)
        }

        return {
            'text': text,
            'metadata': metadata
        }


